export const options = [
	'Hello',
	'How are you?',
	'What is your name?',
	'Goodbye',
	'See you later',
	'Yes',
	'No',
	'Maybe',
	'Please',
	'Thank you',
	'Sorry',
	'Help',
	'I don\'t know',
	'I am not sure',
	'Can you repeat that?',
	'I need assistance',
	'I am fine',
	'I am good',
	'I am not feeling well',
	'Can I help you?',
];
